# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scrabble

on: [ push ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

        source $HOME/.poetry/env
        poetry config virtualenvs.create false --local
        poetry install
    - name: Lint with flake8
      run: |
        flake8 scrabble/ tests/ run_cmd.py --count --show-source --statistics
    - name: Lint with isort
      run: |
        isort -c
    - name: Lint with mypy
      run: |
        mypy --ignore-missing-imports scrabble/ tests/ run_cmd.py
    - name: Test with pytest
      run: |
        python -m pytest tests/ -vvv
